"""subnet version, supernet

Revision ID: 1912ff318f85
Revises: 
Create Date: 2023-06-05 18:10:33.595687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912ff318f85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_id'), 'section', ['id'], unique=False)
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    op.create_table('subnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('supernet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_id'), 'subnet', ['id'], unique=False)
    op.create_index(op.f('ix_subnet_ip'), 'subnet', ['ip'], unique=False)
    op.create_index(op.f('ix_subnet_name'), 'subnet', ['name'], unique=False)
    op.create_index(op.f('ix_subnet_version'), 'subnet', ['version'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.Boolean(), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_id'), 'host', ['id'], unique=False)
    op.create_index(op.f('ix_host_ip'), 'host', ['ip'], unique=False)
    op.create_index(op.f('ix_host_name'), 'host', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_name'), table_name='host')
    op.drop_index(op.f('ix_host_ip'), table_name='host')
    op.drop_index(op.f('ix_host_id'), table_name='host')
    op.drop_table('host')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subnet_version'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_name'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_ip'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_id'), table_name='subnet')
    op.drop_table('subnet')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.drop_index(op.f('ix_section_id'), table_name='section')
    op.drop_table('section')
    # ### end Alembic commands ###
