"""roles

Revision ID: 34d1fa151f4c
Revises: e8921a3ab854
Create Date: 2023-06-04 18:00:08.320398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d1fa151f4c'
down_revision = 'e8921a3ab854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('operator', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('superuser', sa.Boolean(), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'superuser')
    op.drop_column('user', 'operator')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
