"""Create cascade delete

Revision ID: 5c55259cb852
Revises: 
Create Date: 2023-05-17 22:29:52.887938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c55259cb852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_v4', sa.String(), nullable=True),
    sa.Column('ip_v6', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_id'), 'subnet', ['id'], unique=False)
    op.create_index(op.f('ix_subnet_ip_v4'), 'subnet', ['ip_v4'], unique=False)
    op.create_index(op.f('ix_subnet_ip_v6'), 'subnet', ['ip_v6'], unique=False)
    op.create_index(op.f('ix_subnet_location'), 'subnet', ['location'], unique=False)
    op.create_index(op.f('ix_subnet_name'), 'subnet', ['name'], unique=True)
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_v4', sa.Integer(), nullable=True),
    sa.Column('ip_v6', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_id'), 'host', ['id'], unique=False)
    op.create_index(op.f('ix_host_ip_v4'), 'host', ['ip_v4'], unique=False)
    op.create_index(op.f('ix_host_ip_v6'), 'host', ['ip_v6'], unique=False)
    op.create_index(op.f('ix_host_name'), 'host', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_name'), table_name='host')
    op.drop_index(op.f('ix_host_ip_v6'), table_name='host')
    op.drop_index(op.f('ix_host_ip_v4'), table_name='host')
    op.drop_index(op.f('ix_host_id'), table_name='host')
    op.drop_table('host')
    op.drop_index(op.f('ix_subnet_name'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_location'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_ip_v6'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_ip_v4'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_id'), table_name='subnet')
    op.drop_table('subnet')
    # ### end Alembic commands ###
