"""Add subnet and relationship

Revision ID: c7935b691198
Revises: 
Create Date: 2023-03-29 23:30:42.027364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7935b691198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_v4', sa.Integer(), nullable=True),
    sa.Column('ip_v6', sa.Integer(), nullable=True),
    sa.Column('mask', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_id'), 'subnet', ['id'], unique=False)
    op.create_index(op.f('ix_subnet_ip_v4'), 'subnet', ['ip_v4'], unique=True)
    op.create_index(op.f('ix_subnet_ip_v6'), 'subnet', ['ip_v6'], unique=True)
    op.create_index(op.f('ix_subnet_mask'), 'subnet', ['mask'], unique=False)
    op.create_index(op.f('ix_subnet_name'), 'subnet', ['name'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_v4', sa.Integer(), nullable=True),
    sa.Column('ip_v6', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.create_index(op.f('ix_address_ip_v4'), 'address', ['ip_v4'], unique=True)
    op.create_index(op.f('ix_address_ip_v6'), 'address', ['ip_v6'], unique=True)
    op.create_index(op.f('ix_address_name'), 'address', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_name'), table_name='address')
    op.drop_index(op.f('ix_address_ip_v6'), table_name='address')
    op.drop_index(op.f('ix_address_ip_v4'), table_name='address')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_subnet_name'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_mask'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_ip_v6'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_ip_v4'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_id'), table_name='subnet')
    op.drop_table('subnet')
    # ### end Alembic commands ###
