"""Change host ipv4 and ipv6 to flexible ip

Revision ID: e472e61333f5
Revises: 2983e0d6fe0b
Create Date: 2023-05-19 22:13:56.191332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e472e61333f5'
down_revision = '2983e0d6fe0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('ip', sa.Integer(), nullable=True))
    op.drop_index('ix_host_ip_v4', table_name='host')
    op.drop_index('ix_host_ip_v6', table_name='host')
    op.create_index(op.f('ix_host_ip'), 'host', ['ip'], unique=False)
    op.drop_column('host', 'ip_v6')
    op.drop_column('host', 'ip_v4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('ip_v4', sa.INTEGER(), nullable=True))
    op.add_column('host', sa.Column('ip_v6', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_host_ip'), table_name='host')
    op.create_index('ix_host_ip_v6', 'host', ['ip_v6'], unique=False)
    op.create_index('ix_host_ip_v4', 'host', ['ip_v4'], unique=False)
    op.drop_column('host', 'ip')
    # ### end Alembic commands ###
